apiVersion: v1
kind: Pod
metadata:
  name: my-multicontainer-pod
spec:
  containers:
    - name: main-app
      image: python:3.9-slim
      command: ["python", "-m", "http.server", "8080"]
      ports:
        - containerPort: 8080

    - name: log-shipper
      image: busybox
      command: ["sh", "-c", "tail -F /var/log/app.log | log-stash-endpoint"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

  volumes:
    - name: shared-logs
      emptyDir: {}

